language: php

php:
  - '7.1'

services:
  - docker

install:
  - docker build -t php-webserver .
  - >
    docker run -d 
    -p 127.0.0.1:80:80 
    -e
      APP_ENV="dev"
      NGINX_VERSION="1.13.7"
      NGINX_WEBROOT="/var/www/html"
      NGINX_PROXY_FORWARD_HTTPS="0"
      PHP_MEMORY_LIMIT="256M"
      PHP_MAX_EXEC_TIME="60"
      PHP_UPLOAD_MAX_FILESIZE="256M"
      PHP_POST_MAX_SIZE="256M"
      PHP_FPM_PM="dynamic"
      PHP_FPM_PM_MAX_CHILDREN="10"
      PHP_FPM_PM_MAX_REQUESTS="500"
      PHP_FPM_PM_START_SERVERS="4"
      PHP_FPM_PM_MIN_SPARE_SERVERS="2"
      PHP_FPM_PM_MAX_SPARE_SERVERS="6"
      SMTP_HOSTNAME=""
      SMTP_PORT="587"
      SMTP_FROM=""
      SMTP_USERNAME=""
      SMTP_PASSWORD=""
      SMTP_AUTH="1"
      SMTP_TLS="1"
      RDS_HOSTNAME=""
      RDS_DB_NAME=""
      RDS_USERNAME=""
      RDS_PASSWORD=""
      --name testing-php-webserver
      php-webserver

before_script:
  - composer require guzzlehttp/guzzle hamcrest/hamcrest-php

#TODO: what to test?
# - get request and verify 200 etc
# - check copy in scripts from src
# - check if scripts are called (+ in right order)
# - check vars in configs
# - check fakemail


script:
  - docker ps
  - sleep 5
  - curl -I 127.0.0.1:80
  - python .travis/tests.py

notifications:
  slack: ngineered:EIKJFrzibOe0TwUhLXNe8Q2Q
